### ISSUE TITLE
Build fails with `./build.sh: line 56: ../zephyr/zephyr-env.sh: No such file or directory`

### ISSUE THREAD

**Issue by paulmenzel** [intel/pse-fw#1]
Following the instructions in the README to build the defaul hello world application, it fails like below:

    $ git log --oneline --no-decorate -1
    dd8eafa Update licenses
    $ ./build.sh
    Building pse_base app
    ./build.sh: line 56: ../zephyr/zephyr-env.sh: No such file or directory
    ./build.sh: line 57: west: command not found
    Build Failed

**Comment by kumarnac** [comment]
Thanks for pointing out. A detailed document with  dependencies and  build steps  has been added in the docs folder.

**Comment by paulmenzel** [comment]
Thank you. That is commit https://github.com/intel/pse-fw/commit/688307bdd1e02420b144f5926e49872286a8adb2. (Why not reference the issue next time with a *Resolves* tag? ;-))

A PDF document is rather uncommon in my experience, and a text document, marked up with Markdown or similar, would be very appreciated.
